### ISSUE TITLE
Link to documentation in Korp v6.0.1 is broken

### ISSUE THREAD

**Issue by Trondtr** [giellatekno/korp-frontend#1]
The link is 
https://spraakbanken.gu.se/verktyg/korp/anv%E4ndarhandledning
and should be
https://spraakbanken.gu.se/verktyg/korp/anv%C3%A4ndarhandledning
thus %C3%A4 (UTF-8 encoding) rather than Latin1 encoding.

In addition, we should have more documentation links.

**Comment by carges** [comment]
This is now fixed
