### ISSUE TITLE
Open issues in localisation

### ISSUE THREAD

**Issue by Trondtr** [giellatekno/korp-frontend#12]
New language names are not translated.

**Comment by Trondtr** [comment]
Nowegian:
Kven texts Meänkieli texts Veps texts Võro texts fao_texts olo_texts Parallelltekster 
Finnish:
Kven texts Meänkieli texts Veps texts Võro texts fao_texts olo_texts Rinnakkaistekstit

**Comment by Trondtr** [comment]
I now added language names for fi, nb, se, ru, as well as a new line "russian":"По-русски". Give it a try.

**Comment by carges** [comment]
Localisation is now fixed for f_korp. Russian option is now added to the right menu. 
There are still few labels not translated, maybe @Trondtr can have a look at them?

**Comment by Trondtr** [comment]
I will go through them. The translated menus really look much nicer than the untranslated ones.

**Comment by Trondtr** [comment]
Ok, I now went through the localisation files and translated what I found. => Update, and we'll have a look.

**Comment by carges** [comment]
Localisation is now fixed for both f_korp and u_korp
