### ISSUE TITLE
The menu with "word" as default in the Extended search box is flawed

### ISSUE THREAD

**Issue by Trondtr** [giellatekno/korp-frontend#2]
The menu has three submenus ("word", "word attributes", "text attributes". Several of them are not translated at all. Compared to both the SIKOR korp (Saami) and the newest Korp in Gothenburg, the time period search box is also missing.

**Comment by carges** [comment]
The relevant attributes are now translated and the rest removed. 
The time period will appear again when time-data is implemented (see Issue#4 https://github.com/giellatekno/korp-frontend/issues/4).
