### ISSUE TITLE
Year: is missing at the rightmost metadata box in u_korp, korp versions 

### ISSUE THREAD

**Issue by Trondtr** [giellatekno/korp-frontend#3]
v6.0.1 has:
Corpus
      Non-fiction texts
text attributes
      title: Марий литератур
      domain: facts

We do want at least "year", perhaps also "author"
Corpus
      Non-fiction texts
text attributes
      year: 1998
      title: Марий литератур
      author: Юрий Артамонов
      domain: facts

**Comment by carges** [comment]
There is now date attribute in the metadata box to the right.
