### ISSUE TITLE
Year graph missing in u_korp

### ISSUE THREAD

**Issue by Trondtr** [giellatekno/korp-frontend#4]
The corpus bar to the right of the KORP logo usually contains  a year graph (both for gtweb.uit.no/korp, for the Gothenburg corpus, but neither for u_korp nor for f_korp. Especially for u_korp this is needed, since a very high portion of the u_korp corpora are annotated for publication year. For f_corp, the number is lower, but here we should add the graph in order to motivate ourself to add such data.

**Comment by carges** [comment]
Year graph is now in place for u_korp.
