### ISSUE TITLE
The pop-up documentation on the tags for u_korp is not in place

### ISSUE THREAD

**Issue by Trondtr** [giellatekno/korp-frontend#6]
in Saami korp, placing the mouse over the analysis in the right box will give an explanation. This is not in place for u_korp. Either the file is not in place, or it is not linked to. @carges , where do I find the (missing|not-yet-linked) file?

korp:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/11891083/104289339-4b10b080-54b9-11eb-9a0d-5f6221aba453.png">
u_korp:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/11891083/104289385-595ecc80-54b9-11eb-8727-4e63b502bd92.png">

**Comment by carges** [comment]
this is now fixed
